dir:
    "../DRIP_Seq/pipeline_test"

samples:
    ["D1255C07"]

data_type:
    "PE"

threads:
    12

aligner:
    "bwa_mem"

hmm_thresh:
    5

hmm_winS:
    15

bin_size:
    1000

binlist: 
    ["1", "10", "20", "50", "100", "250", "500", "1000"]